#!/usr/bin/env bash
# cc-note.sh - Generate session hand-off note template
# ---------------------------------------------
# Usage:  cc-hooks/cc-note.sh [--yes]
#   --yes   : non-interactive; overwrite existing file if any
#
# This script creates a Markdown hand-off note under
#   ./.ccflow/NOTE/YYYY-MM-DD-HHMM-handoff.md
# with a pre-formatted template.  It is safe to rerun; if the target file
# already exists it opens the file in $EDITOR unless --yes is given.
# ---------------------------------------------
set -euo pipefail

YES_MODE=false
if [[ "${1:-}" == "--yes" ]]; then
  YES_MODE=true
fi

# Determine timestamp (local time)
TS=$(date +"%Y-%m-%d-%H%M")
NOTE_DIR=".ccflow/NOTE"
FILE="${NOTE_DIR}/${TS}-handoff.md"

mkdir -p "$NOTE_DIR"

if [[ -f "$FILE" && $YES_MODE == false ]]; then
  echo "[cc-note] $FILE already exists. Open in \$EDITOR? [y/N]" >&2
  read -r ans
  [[ "$ans" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 1; }
fi

cat > "$FILE" <<EOF
# セッション申し送り - ${TS}

## 🎯 セッション概要
- **開始時刻**: <!-- 例: 2025-07-21 09:00 -->
- **終了時刻**: <!-- 例: 2025-07-21 17:30 -->
- **環境**: <!-- bash 5.1, git 2.40 など -->
- **作業時間**: <!-- 例: 6時間30分 -->

## ✅ 完了した作業
### [L] 低複雑度タスク
- 
### [M] 中複雑度タスク
- 
### [H] 高複雑度タスク
- 

## 🔄 進行中の作業
### 現在の状況
- 
### 技術的決定事項
- 
### 発見された課題
- 

## 📋 次回セッションへの引き継ぎ
1. 
2. 

## 🧠 推奨次回アクション
- 

## 📊 パフォーマンス・メトリクス
- 

---
*Generated by cc-note.sh*
EOF

printf "[cc-note] Created %s\n" "$FILE"
