name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  bootstrap-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Run bootstrap script and validate JSON
        run: bash .claude/hooks/bootstrap.sh <<< "" | jq .
